apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: sidecart1 
spec:
 containers: # NOTE THAT BELOW HERE WE CAN ADD AS MANY CONTAINERS WE WISH TO ENCAPSULATE IN THE SAME POD
 - name: my-animals 
   image: supergiantkir/animals:bear 
   ports: 
   - containerPort: 80
   volumeMounts:
    - name: app-storage
      mountPath: /storage
 - name: springapp
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 8080
   volumeMounts:
    - name: app-storage
      mountPath: /storage
 volumes:
 - name: app-storage
   hostPath:
      # directory location on host
      path: /data
