apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: music
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.pods.image }}:{{ .Values.pods.tag }}
        ports:
        - containerPort: 8080
