apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }}
  labels:
{{- include "spring.labels" . | trim | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "spring.labels" . | trim | nindent 6 }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
      {{- include "spring.labels" . | trim | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.pods.repo }}/{{ .Values.pods.image }}:{{ .Values.pods.tag }}
        ports:
        - containerPort: 8080
