kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: music
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.name }}
    protocol: TCP
    port: 80
    targetPort: 8080
