kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
{{- include "spring.labels" . | trim | nindent 4}}
  {{- if eq .Values.deployment.ingress false }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
  - name: {{ .Values.service.name }}
    protocol: TCP
    port: 80
    targetPort: 8080
